name: Update Profile Animations

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      # Snake Animation
      - uses: Platane/snk@v3
        with:
          github_user_name: pypi-ahmad
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg

      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 3D Contribution Graph
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: pypi-ahmad

      - name: Commit & Push
        run: |
          git config user.name pypi-ahmad
          git config user.email pypi.ahmad@gmail.com
          git add -A .
          git commit -m "Generated 3D graph" || echo "No changes"
          git push origin main
